### PR TITLE
Delete all from master

### PR DESCRIPTION
**Pull request by ganolmc**
Task 11 finished

### CODE REVIEW

**Comment by AleshaOleg** [comment]
Please provide a link to a demo.

**Comment by ganolmc** [comment]
https://ganolmc.github.io/checkout/

**Comment by AleshaOleg** [comment]
screen shot 2018-01-27 at 3 02 49 pm

Use PNG/SVG to remove the white background from images.

**Comment by AleshaOleg** [comment]
screen shot 2018-01-27 at 3 03 57 pm
Wrong paddings

**Comment by AleshaOleg** [comment]
Use `<label>` with checkbox

**Comment by ganolmc** [comment]
Fixed!

**Comment by AleshaOleg** [comment]
@ganolmc `<label>` still not working properly. Please read docs about the usage of `label`.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

**Comment by ganolmc** [comment]
I've fixed with label! Could you check, please?

**Comment by ganolmc** [comment]
I'm not sure what I must do next. Needed to be merged?

**Review by AleshaOleg — APPROVED** [review]

**Pull request merged**
